### ISSUE TITLE
CubeFile label parsing fails in Python3

### ISSUE THREAD

**Issue by michaelaye** [wtolson/pysis#7]
Here's the traceback:

```python
---------------------------------------------------------------------------
ParseError                                Traceback (most recent call last)
<ipython-input-5-cfaa5504a97c> in <module>()
----> 1 cube = CubeFile('N1595337202_1.map.cal.cub')

/Users/klay6683/Dropbox/src/Pysis/pysis/cubefile.py in __init__(self, stream, filename)
     50 
     51         #: The parsed label header in dictionary form.
---> 52         self.label = self._parse_label(stream)
     53 
     54         #: A numpy array representing the image data.

/Users/klay6683/Dropbox/src/Pysis/pysis/cubefile.py in _parse_label(self, stream)
    223 
    224     def _parse_label(self, stream):
--> 225         return load_label(stream)
    226 
    227     def _parse_data(self, stream):

/Users/klay6683/Dropbox/src/Pysis/pysis/labels/__init__.py in load(stream)
     15     if isinstance(stream, six.string_types):
     16         with open(stream, 'rb') as fp:
---> 17             return LabelDecoder().decode(fp)
     18     return LabelDecoder().decode(stream)
     19 

/Users/klay6683/Dropbox/src/Pysis/pysis/labels/decoder.py in decode(self, stream)
    202             stream = BufferedStream(stream)
    203 
--> 204         label = Label(self.parse_block(stream, self.has_end))
    205         self.skip_end(stream)
    206         return label

/Users/klay6683/Dropbox/src/Pysis/pysis/labels/decoder.py in parse_block(self, stream, has_end)
    220                 return statements
    221 
--> 222             statements.append(self.parse_statement(stream))
    223 
    224     def skip_whitespace_or_comment(self, stream):

/Users/klay6683/Dropbox/src/Pysis/pysis/labels/decoder.py in parse_statement(self, stream)
    256 
    257         if self.has_object(stream):
--> 258             return self.parse_object(stream)
    259 
    260         if self.has_assignment(stream):

/Users/klay6683/Dropbox/src/Pysis/pysis/labels/decoder.py in parse_object(self, stream)
    379 
    380         self.skip_statement_delimiter(stream)
--> 381         statements = self.parse_block(stream, self.has_end_object)
    382 
    383         self.expect_in(stream, self.end_object_tokens)

/Users/klay6683/Dropbox/src/Pysis/pysis/labels/decoder.py in parse_block(self, stream, has_end)
    220                 return statements
    221 
--> 222             statements.append(self.parse_statement(stream))
    223 
    224     def skip_whitespace_or_comment(self, stream):

/Users/klay6683/Dropbox/src/Pysis/pysis/labels/decoder.py in parse_statement(self, stream)
    253         """
    254         if self.has_group(stream):
--> 255             return self.parse_group(stream)
    256 
    257         if self.has_object(stream):

/Users/klay6683/Dropbox/src/Pysis/pysis/labels/decoder.py in parse_group(self, stream)
    348 
    349         self.skip_statement_delimiter(stream)
--> 350         statements = self.parse_block(stream, self.has_end_group)
    351 
    352         self.expect_in(stream, self.end_group_tokens)

/Users/klay6683/Dropbox/src/Pysis/pysis/labels/decoder.py in parse_block(self, stream, has_end)
    220                 return statements
    221 
--> 222             statements.append(self.parse_statement(stream))
    223 
    224     def skip_whitespace_or_comment(self, stream):

/Users/klay6683/Dropbox/src/Pysis/pysis/labels/decoder.py in parse_statement(self, stream)
    261             return self.parse_assignment(stream)
    262 
--> 263         self.raise_unexpected(stream)
    264 
    265     def has_whitespace(self, stream, offset=0):

/Users/klay6683/Dropbox/src/Pysis/pysis/labels/decoder.py in raise_unexpected(self, stream, token)
    152         if token is None:
    153             token = self.peek(stream, 1)
--> 154         self.raise_error('Unexpected token %r' % token, stream)
    155 
    156     def raise_unexpected_eof(self, stream):

/Users/klay6683/Dropbox/src/Pysis/pysis/labels/decoder.py in raise_error(self, msg, stream)
    129 
    130     def raise_error(self, msg, stream):
--> 131         raise ParseError(msg, stream.pos, stream.lineno, stream.colno)
    132 
    133     def optional(self, stream, token):

ParseError: Unexpected token b'#': line 31 column 5 (char 699)
```

**Comment by michaelaye** [comment]
same error in Python2 though.

**Comment by wtolson** [comment]
Are you able to paste the label its trying to parse?

**Comment by michaelaye** [comment]
There you go:
https://gist.github.com/michaelaye/e2e2d8f6a92a99cd336b

**Comment by michaelaye** [comment]
It doesn't like the '#'

**Comment by wtolson** [comment]
Ah, looks like its tripping up on the line comments. I wasn't ever able to find that in the spec but good to know it exists in the wild. Shouldn't be to bad to add that language feature.

**Comment by wtolson** [comment]
Just pushed support to master. Mind seeing if it works for you?

**Comment by michaelaye** [comment]
Not at all.
Both py2 and 3 give me now this:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-0e0966b002d2> in <module>()
----> 1 cube = CubeFile(fname)

/Users/klay6683/Dropbox/src/Pysis/pysis/cubefile.pyc in __init__(self, stream, filename)
     53 
     54         #: A numpy array representing the image data.
---> 55         self.data = self._parse_data(stream)
     56 
     57     def apply_scaling(self, copy=True):

/Users/klay6683/Dropbox/src/Pysis/pysis/cubefile.pyc in _parse_data(self, stream)
    226 
    227     def _parse_data(self, stream):
--> 228         stream.seek(self.start_byte)
    229 
    230         if self.format == 'BandSequential':

AttributeError: 'str' object has no attribute 'seek'
```

**Comment by michaelaye** [comment]
hm, something weird with my setup, i have lot's of python2 print messages when i try to install on python 3?
```bash
creating /Users/klay6683/miniconda3/lib/python3.4/site-packages/pysis-0.5.0-py3.4.egg
Extracting pysis-0.5.0-py3.4.egg to /Users/klay6683/miniconda3/lib/python3.4/site-packages
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/pysis-0.5.0-py3.4.egg/pysis/commands.py", line 57
    print ' '.join(self.get_cmd(**kwargs))
            ^
SyntaxError: invalid syntax

  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/pysis-0.5.0-py3.4.egg/pysis/labels.py", line 63
    print msg
            ^
SyntaxError: Missing parentheses in call to 'print'

Removing Pysis 0.5.0 from easy-install.pth file
Adding pysis 0.5.0 to easy-install.pth file

Installed /Users/klay6683/miniconda3/lib/python3.4/site-packages/pysis-0.5.0-py3.4.egg
Processing dependencies for pysis==0.5.0
Finished processing dependencies for pysis==0.5.0
```

**Comment by michaelaye** [comment]
Ok, on Python 2 I get this now, guess I had  a stale egg somewhere:

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-c2d57d04a492> in <module>()
----> 1 from pyciss.io import CubeFile

/Users/klay6683/Dropbox/src/pyciss/pyciss/io.py in <module>()
      1 import os
----> 2 from pysis import CubeFile
      3 import matplotlib.pyplot as plt
      4 import numpy as np
      5 

/Users/klay6683/miniconda3/envs/py27/lib/python2.7/site-packages/pysis-0.5.0-py2.7.egg/pysis/__init__.py in <module>()
     24 from .isiscommand import Isis
     25 from .isispool import IsisPool
---> 26 from .cubefile import CubeFile
     27 from .env import (
     28     ISIS_ROOT,

/Users/klay6683/miniconda3/envs/py27/lib/python2.7/site-packages/pysis-0.5.0-py2.7.egg/pysis/cubefile.py in <module>()
      4 from six.moves import range
      5 
----> 6 from .labels import load as load_label
      7 from .specialpixels import SPECIAL_PIXELS
      8 

ImportError: cannot import name load
```

**Comment by michaelaye** [comment]
this still fails on Python 3:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-2cc467d3253b> in <module>()
----> 1 cube = RingCube('N1595337202_1.map.cal.cub')

/Users/klay6683/miniconda3/lib/python3.4/site-packages/pysis-0.5.0-py3.4.egg/pysis/cubefile.py in __init__(self, stream, filename)
     53 
     54         #: A numpy array representing the image data.
---> 55         self.data = self._parse_data(stream)
     56 
     57     def apply_scaling(self, copy=True):

/Users/klay6683/miniconda3/lib/python3.4/site-packages/pysis-0.5.0-py3.4.egg/pysis/cubefile.py in _parse_data(self, stream)
    226 
    227     def _parse_data(self, stream):
--> 228         stream.seek(self.start_byte)
    229 
    230         if self.format == 'BandSequential':

AttributeError: 'str' object has no attribute 'seek'
```

**Comment by michaelaye** [comment]
Here's a link to the file, if you want to try for yourself:

https://dl.dropboxusercontent.com/u/139035/N1595337202_1.map.cal.cub

**Comment by wtolson** [comment]
Ah, the CubeFile constructor expects a file-like object. If you want to open a file on disk, use the open helper:

    image = CubeFile.open('N1595337202_1.map.cal.cub')

**Comment by michaelaye** [comment]
but it works on 2.7?

**Comment by wtolson** [comment]
Not it should through a similar error in 2.7. I've put in a check to through a more explanatory error in 9d3c814042d43897c0d95fdd2e2fdbfd3665d543. Should see something like this now if you try to pass a string to the constructor:

    In [7]: CubeFile('N1595337202_1.map.cal.cub')
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-7-9a54f117ed2d> in <module>()
    ----> 1 CubeFile('N1595337202_1.map.cal.cub')

    /Users/wto/workspace/pysis/pysis/cubefile.py in __init__(self, stream, filename)
         53                 'Use %s.open(filename) to open a image file.'
         54             )
    ---> 55             raise TypeError(error_msg % type(self).__name__)
         56 
         57         #: The filename if given, otherwise none.

    TypeError: A file like object is expected for stream. Use CubeFile.open(filename) to open a image file.

**Comment by michaelaye** [comment]
yeah, sorry. I thought I had this asymmetry before. Thanks! Closing.
